# Generated by Django 5.1.3 on 2024-11-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadonne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='langue',
            name='code_iso',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='langue',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
