# Generated by Django 5.1.3 on 2024-11-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadonne', '0003_genre_created_at_genre_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musique',
            old_name='document_id',
            new_name='document',
        ),
    ]
