# Generated by Django 5.1.3 on 2024-11-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadonne', '0004_rename_document_id_musique_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='document_id',
            new_name='document',
        ),
    ]
