# Generated by Django 5.1.3 on 2024-11-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadonne', '0005_rename_document_id_film_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clipmusicale',
            old_name='document_id',
            new_name='document',
        ),
    ]
